# Matrizes

## Definindo matrizes no python

In [1]:
import numpy as np

In [5]:
M = np.array([[1,0],[0,-1]])
print(M)

[[ 1  0]
 [ 0 -1]]


## Operações com matrizes

### Multiplicação por um número 

In [6]:
import numpy as np

In [14]:
M2 = np.array([[3,0,4],[0,2,1],[1,6,8]])
print(M2)

[[3 0 4]
 [0 2 1]
 [1 6 8]]


In [16]:
(5/2)*M2

array([[ 7.5,  0. , 10. ],
       [ 0. ,  5. ,  2.5],
       [ 2.5, 15. , 20. ]])

### Soma de matrizes 

In [17]:
import numpy as np

In [19]:
M3 = np.array([[1,3],[5,-1]])
print(M3)

[[ 1  3]
 [ 5 -1]]


In [20]:
M4 = np.array([[2,6],[5,-9]])
print(M4)

[[ 2  6]
 [ 5 -9]]


In [21]:
M3+M4

array([[  3,   9],
       [ 10, -10]])

In [22]:
M3-M4

array([[-1, -3],
       [ 0,  8]])

### Multiplicação de matrizes 

In [32]:
import numpy as np

In [28]:
M5 = np.array([[1,7],[5,-2]])
print(M5)

[[ 1  7]
 [ 5 -2]]


In [29]:
M6 = np.array([[2,0],[0,3]])
print(M6)

[[2 0]
 [0 3]]


In [30]:
M5@M6

array([[ 2, 21],
       [10, -6]])

In [31]:
M6@M5

array([[ 2, 14],
       [15, -6]])

### Matriz transposta 

In [33]:
import numpy as np

In [35]:
print(M)

[[3 0 4]
 [0 2 1]
 [1 6 8]]


In [36]:
M.T

array([[3, 0, 1],
       [0, 2, 6],
       [4, 1, 8]])

### Divisão de matrizes 

In [42]:
import numpy as np

In [43]:
print(M5)

[[ 1  7]
 [ 5 -2]]


In [44]:
print(M6)

[[2 0]
 [0 3]]


In [45]:
M6/M5

array([[ 2. ,  0. ],
       [ 0. , -1.5]])