# Vetores Complexos

## Notação de Dirac

Bra  $\equiv \langle \Psi |$

Ket $\equiv |\Psi \rangle $ 

Braket $\equiv \langle \Psi | \Psi \rangle$

### Teoria 

$ |\Psi \rangle \equiv \begin{bmatrix}
a_1 \\
a_2 \\
. \\
. \\
. \\
a_n \\
\end{bmatrix}$ 

$ \langle \Psi |\equiv\begin{bmatrix}
a_1 & a_2 & ... & a_n \\
\end{bmatrix}$

Produto interno: $\langle \Psi^* | \Psi \rangle\equiv\begin{bmatrix}
a_1^* & a_2^* & ... & a_n^* \\
\end{bmatrix}$ 
$\begin{bmatrix}
a_1 \\
a_2 \\
. \\
. \\
. \\
a_n \\
\end{bmatrix}$

Produto externo:$ |\Psi \rangle\langle \Psi^* |\equiv\begin{bmatrix}
a_1 \\
a_2 \\
. \\
. \\
. \\
a_n \\
\end{bmatrix}$$\begin{bmatrix}
a_1^* & a_2^* & ... & a_n^* \\
\end{bmatrix}$ 

Produto tensorial: $ |\Phi \rangle 	\otimes  |\Psi \rangle \equiv$
$\begin{bmatrix}
v_{1} w_{1} & v_{1} w_{2} & \cdots & v_{1} w_{m} \\
v_{2} w_{1} & v_{2} w_{2} & \cdots & v_{2} w_{m} \\
\vdots & \vdots & \ddots & \vdots \\
v_{n} w_{1} & v_{n} w_{2} & \cdots & v_{n} w_{m}\end{bmatrix}$

## Usando vetores no python 

### Definindo os vetores básicos

Definindo o vetor  $|0\rangle$

In [8]:
import numpy as np

In [9]:
ket0 = np.array([[1],[0]])
print(ket0)

[[1]
 [0]]


Definindo o vetor  $\langle0|$

In [7]:
bra0 = np.conjugate(ket0).T
print(bra0)

[[1 0]]


Definindo o vetor  $|1\rangle$

In [10]:
ket1 = np.array([[0],[1]])
print(ket1)

[[0]
 [1]]


Definindo o vetor  $\langle 1|$

In [11]:
bra1 = np.conjugate(ket1).T
print(bra1)

[[0 1]]


### Operações com os vetores

#### Produto interno

$\langle 0 | 1 \rangle\equiv\begin{bmatrix}
1 & 0\\
\end{bmatrix}$ 
$\begin{bmatrix}
0 \\
1 \\
\end{bmatrix}$

In [12]:
bra0@ket1

array([[0]])

$\langle 1 | 0 \rangle\equiv\begin{bmatrix}
0 & 1\\
\end{bmatrix}$ 
$\begin{bmatrix}
1 \\
0 \\
\end{bmatrix}$

In [14]:
bra1@ket0

array([[0]])

#### Produto externo

$|1 \rangle\langle 0 |\equiv\begin{bmatrix}
0 \\
1\\
\end{bmatrix}$ $\begin{bmatrix}
1 & 0\
\end{bmatrix}$ 


In [15]:
ket1@bra0

array([[0, 0],
       [1, 0]])

$|0 \rangle\langle 1 |\equiv\begin{bmatrix}
1 \\
0\\
\end{bmatrix}$ $\begin{bmatrix}
0 & 1\
\end{bmatrix}$ 


In [16]:
ket0@bra1

array([[0, 1],
       [0, 0]])

#### Produto tensorial

In [20]:
import sympy
from sympy import Matrix
from sympy.physics.quantum import TensorProduct

$ |0 \rangle 	\otimes  |0 \rangle \equiv$
$\begin{bmatrix}
1 \\
0\\
\end{bmatrix}$ $\begin{bmatrix}
1 \\
0\\
\end{bmatrix}$

In [25]:
TensorProduct(ket0,ket0)

array([[1],
       [0],
       [0],
       [0]])

$ |0 \rangle 	\otimes  |1 \rangle \equiv$
$\begin{bmatrix}
1 \\
0\\
\end{bmatrix}$ $\begin{bmatrix}
0 \\
1\\
\end{bmatrix}$

In [27]:
TensorProduct(ket0,ket1)

array([[0],
       [1],
       [0],
       [0]])

$ |1 \rangle 	\otimes  |0 \rangle \equiv$
$\begin{bmatrix}
0 \\
1\\
\end{bmatrix}$ $\begin{bmatrix}
1 \\
0\\
\end{bmatrix}$

In [28]:
TensorProduct(ket1,ket0)

array([[0],
       [0],
       [1],
       [0]])

$ |1 \rangle 	\otimes  |1 \rangle \equiv$
$\begin{bmatrix}
0 \\
1\\
\end{bmatrix}$ $\begin{bmatrix}
0 \\
1\\
\end{bmatrix}$

In [29]:
TensorProduct(ket1,ket1)

array([[0],
       [0],
       [0],
       [1]])